import type { Metadata } from "next";
import { Protest_Strike, Play } from "next/font/google";
import "./globals.css";

const protestStrike = Protest_Strike({
  variable: "--font-protest-strike",
  subsets: ["latin"],
  weight: "400",
});

const play = Play({
  variable: "--font-play",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`${protestStrike.variable} ${play.variable} antialiased font-play`}
      >
        {children}
      </body>
    </html>
  );
}
